### ISSUE TITLE
React Native iOS addMessageListener issue

### ISSUE THREAD

**Issue by jitvarpatil** [cometchat-pro-samples/react-native-chat-app#1]
When we add message listener it gives the following error:

![Simulator Screen Shot - iPhone X - 2019-04-24 at 04 26 59](https://user-images.githubusercontent.com/18652749/56621198-3d622a00-6649-11e9-8798-2aa02d252590.png)

**Comment by bobo717** [comment]
same

**Comment by anantgarg** [comment]
We have fixed the issue with our latest JS SDK 1.4.2. You can install the new version using the following command:

npm install @cometchat-pro/chat@1.4.2 --save
