### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by anantgarg** [cometchat-pro-samples/react-native-chat-app#2]
Logs in xcode

`2019-06-25 15:09:20.475 [info][tid:com.facebook.react.JavaScript] CometChat login Called
2019-06-25 15:09:20.474756-0700 chatApp[7195:1843741] CometChat login Called
2019-06-25 15:09:20.645 [warn][tid:com.facebook.react.JavaScript] Possible Unhandled Promise Rejection (id: 10):
TypeError: undefined is not an object (evaluating 's.localStore.getItem')
http://192.168.0.21:8081/index.bundle?platform=ios&dev=true&minify=false:114641:25
tryCallTwo@http://192.168.0.21:8081/index.bundle?platform=ios&dev=true&minify=false:3165:9
doResolve@http://192.168.0.21:8081/index.bundle?platform=ios&dev=true&minify=false:3329:25
Promise@http://192.168.0.21:8081/index.bundle?platform=ios&dev=true&minify=false:3188:14
get@http://192.168.0.21:8081/index.bundle?platform=ios&dev=true&minify=false:114640:29
http://192.168.0.21:8081/index.bundle?platform=ios&dev=true&minify=false:113554:334
tryCallTwo@http://192.168.0.21:8081/index.bundle?platform=ios&dev=true&minify=false:3165:9
doResolve@http://192.168.0.21:8081/index.bundle?platform=ios&dev=true&minify=false:3329:25
Promise@http://192.168.0.21:8081/index.bundle?platform=ios&dev=true&minify=false:3188:14
login@http://192.168.0.21:8081/index.bundle?platform=ios&dev=true&minify=false:113553:31
cometchatLogin@http://192.168.0.21:8081/index.bundle?platform=ios&dev=true&minify=false:112610:30
buttonPressed@http://192.168.0.21:8081/index.bundle?platform=ios&dev=true&minify=false:112598:28
proxiedMethod@[native code]
touchableHandlePress@http://192.168.0.21:8081/index.bundle?platform=ios&dev=true&minify=false:51131:47
touchableHandlePress@[native code]
_performSideEffectsForTransition@http://192.168.0.21:8081/index.bundle?platform=ios&dev=true&minify=false:50570:36
_performSideEffectsForTransition@[native code]
_receiveSignal@http://192.168.0.21:8081/index.bundle?platform=ios&dev=true&minify=false:50496:46
_receiveSignal@[native code]
touchableHandleResponderRelease@http://192.168.0.21:8081/index.bundle?platform=ios&dev=true&minify=false:50379:26
touchableHandleResponderRelease@[native code]
invokeGuardedCallbackImpl@http://192.168.0.21:8081/index.bundle?platform=ios&dev=true&minify=false:11408:21
invokeGuardedCallback@http://192.168.0.21:8081/index.bundle?platform=ios&dev=true&minify=false:11499:42
invokeGuardedCallbackAndCatchFirstError@http://192.168.0.21:8081/index.bundle?platform=ios&dev=true&minify=false:11503:36
executeDispatch@http://192.168.0.21:8081/index.bundle?platform=ios&dev=true&minify=false:11697:48
executeDispatchesInOrder@http://192.168.0.21:8081/index.bundle?platform=ios&dev=true&minify=false:11717:26
executeDispatchesAndRelease@http://192.168.0.21:8081/index.bundle?platform=ios&dev=true&minify=false:11812:35
forEach@[native code]
forEachAccumulated@http://192.168.0.21:8081/index.bundle?platform=ios&dev=true&minify=false:11802:22
runEventsInBatch@http://192.168.0.21:8081/index.bundle?platform=ios&dev=true&minify=false:11906:27
runExtractedEventsInBatch@http://192.168.0.21:8081/index.bundle?platform=ios&dev=true&minify=false:11913:25
http://192.168.0.21:8081/index.bundle?platform=ios&dev=true&minify=false:12880:36
batchedUpdates$1@http://192.168.0.21:8081/index.bundle?platform=ios&dev=true&minify=false:24086:20
batchedUpdates@http://192.168.0.21:8081/index.bundle?platform=ios&dev=true&minify=false:12822:37
_receiveRootNodeIDEvent@http://192.168.0.21:8081/index.bundle?platform=ios&dev=true&minify=false:12879:23
receiveTouches@http://192.168.0.21:8081/index.bundle?platform=ios&dev=true&minify=false:12909:34
__callFunction@http://192.168.0.21:8081/index.bundle?platform=ios&dev=true&minify=false:2587:49
http://192.168.0.21:8081/index.bundle?platform=ios&dev=true&minify=false:2344:31
__guard@http://192.168.0.21:8081/index.bundle?platform=ios&dev=true&minify=false:2541:15
callFunctionReturnFlushedQueue@http://192.168.0.21:8081/index.bundle?platform=ios&dev=true&minify=false:2343:21
callFunctionReturnFlushedQueue@[native code]
2019-06-25 15:09:20.645527-0700 chatApp[7195:1843741] Possible Unhandled Promise Rejection (id: 10):
TypeError: undefined is not an object (evaluating 's.localStore.getItem')
http://192.168.0.21:8081/index.bundle?platform=ios&dev=true&minify=false:114641:25
tryCallTwo@http://192.168.0.21:8081/index.bundle?platform=ios&dev=true&minify=false:3165:9
doResolve@http://192.168.0.21:8081/index.bundle?platform=ios&dev=true&minify=false:3329:25
Promise@http://192.168.0.21:8081/index.bundle?platform=ios&dev=true&minify=false:3188:14
get@http://192.168.0.21:8081/index.bundle?platform=ios&dev=true&minify=false:114640:29
http://192.168.0.21:8081/index.bundle?platform=ios&dev=true&minify=false:113554:334
tryCallTwo@http://192.168.0.21:8081/index.bundle?platform=ios&dev=true&minify=false:3165:9
doResolve@http://192.168.0.21:8081/index.bundle?platform=ios&dev=true&minify=false:3329:25
Promise@http://192.168.0.21:8081/index.bundle?platform=ios&dev=true&minify=false:3188:14
login@http://192.168.0.21:8081/index.bundle?platform=ios&dev=true&minify=false:113553:31
cometchatLogin@http://192.168.0.21:8081/index.bundle?platform=ios&dev=true&minify=false:112610:30
buttonPressed@http://192.168.0.21:8081/index.bundle?platform=ios&dev=true&minify=false:112598:28
proxiedMethod@[native code]
touchableHandlePress@http://192.168.0.21:8081/index.bundle?platform=ios&dev=true&minify=false:51131:47
touchableHandlePress@[native code]
_performSideEffectsForTransition@http://192.168.0.21:8081/index.bundle?platform=ios&dev=true&minify=false:50570:36
_performSideEffectsForTransition@[native code]
_receiveSignal@http://192.168.0.21:8081/index.bundle?platform=ios&dev=true&minify=false:50496:46
_receiveSignal@[native code]
touchableHandleResponderRelease@http://192.168.0.21:8081/index.bundle?platform=ios&dev=true&minify=false:50379:26
touchableHandleResponderRelease@[native code]
invokeGuardedCallbackImpl@http://192.168.0.21:8081/index.bundle?platform=ios&dev=true&minify=false:11408:21
invokeGuardedCallback@http://192.168.0.21:8081/index.bundle?platform=ios&dev=true&minify=false:11499:42
invokeGuardedCallbackAndCatchFirstError@http://192.168.0.21:8081/index.bundle?platform=ios&dev=true&minify=false:11503:36
executeDispatch@http://192.168.0.21:8081/index.bundle?platform=ios&dev=true&minify=false:11697:48
executeDispatchesInOrder@http://192.168.0.21:8081/index.bundle?platform=ios&dev=true&minify=false:11717:26
executeDispatchesAndRelease@http://192.168.0.21:8081/index.bundle?platform=ios&dev=true&minify=false:11812:35
forEach@[native code]
forEachAccumulated@http://192.168.0.21:8081/index.bundle?platform=ios&dev=true&minify=false:11802:22
runEventsInBatch@http://192.168.0.21:8081/index.bundle?platform=ios&dev=true&minify=false:11906:27
runExtractedEventsInBatch@http://192.168.0.21:8081/index.bundle?platform=ios&dev=true&minify=false:11913:25
http://192.168.0.21:8081/index.bundle?platform=ios&dev=true&minify=false:12880:36
batchedUpdates$1@http://192.168.0.21:8081/index.bundle?platform=ios&dev=true&minify=false:24086:20
batchedUpdates@http://192.168.0.21:8081/index.bundle?platform=ios&dev=true&minify=false:12822:37
_receiveRootNodeIDEvent@http://192.168.0.21:8081/index.bundle?platform=ios&dev=true&minify=false:12879:23
receiveTouches@http://192.168.0.21:8081/index.bundle?platform=ios&dev=true&minify=false:12909:34
__callFunction@http://192.168.0.21:8081/index.bundle?platform=ios&dev=true&minify=false:2587:49
http://192.168.0.21:8081/index.bundle?platform=ios&dev=true&minify=false:2344:31
__guard@http://192.168.0.21:8081/index.bundle?platform=ios&dev=true&minify=false:2541:15
callFunctionReturnFlushedQueue@http://192.168.0.21:8081/index.bundle?platform=ios&dev=true&minify=false:2343:21
callFunctionReturnFlushedQueue@[native code]
2019-06-25 15:09:20.799750-0700 chatApp[7195:1843745] [] nw_socket_handle_socket_event [C132.1:1] Socket SO_ERROR [61: Connection refused]
2019-06-25 15:09:20.800920-0700 chatApp[7195:1843745] [] nw_socket_handle_socket_event [C132.2:1] Socket SO_ERROR [61: Connection refused]
2019-06-25 15:09:20.801215-0700 chatApp[7195:1843731] [] nw_connection_get_connected_socket [C132] Client called nw_connection_get_connected_socket on unconnected nw_connection
2019-06-25 15:09:20.801254-0700 chatApp[7195:1843731] TCP Conn 0x2835a2100 Failed : error 0:61 [61]
2019-06-25 15:09:22.984389-0700 chatApp[7195:1843731] [] nw_socket_handle_socket_event [C133.1:1] Socket SO_ERROR [61: Connection refused]
2019-06-25 15:09:22.986824-0700 chatApp[7195:1843731] [] nw_socket_handle_socket_event [C133.2:1] Socket SO_ERROR [61: Connection refused]
2019-06-25 15:09:22.987430-0700 chatApp[7195:1843745] [] nw_connection_get_connected_socket [C133] Client called nw_connection_get_connected_socket on unconnected nw_connection
2019-06-25 15:09:22.987495-0700 chatApp[7195:1843745] TCP Conn 0x2835af180 Failed : error 0:61 [61]`

**Comment by mayur-bhandari** [comment]
Hi @anantgarg, I have fixed the issues. Kindly check and let me know if it is working for you.
