### ISSUE TITLE
error when sending image in chat

### ISSUE THREAD

**Issue by davidweica** [cometchat-pro-samples/react-native-chat-app#3]
got error when taking photo or choosing image from gallery.
![IMG_5606](https://user-images.githubusercontent.com/51187928/61333970-7f7cb100-a7dd-11e9-9024-47de311831e0.PNG)

**Comment by mayur-bhandari** [comment]
@davidweica  What is the extension of image are you trying to send.?

**Comment by davidweica** [comment]
the photos taken in iphone, should be jpeg I guess

David Wei

**Comment by mayur-bhandari** [comment]
@davidweica I have fixed this issue in the last commit. Kindly check on your system. Thank You.
