### ISSUE TITLE
the app becomes frozen after send several text in group chat

### ISSUE THREAD

**Issue by davidweica** [cometchat-pro-samples/react-native-chat-app#5]
tried between iphone and android devices side by side. after sending several messages, the app becomes no response.

**Comment by mayur-bhandari** [comment]
Hi @davidweica , 
We tested our sample app with sending several text messages in group chat but unfortunately we could not recreate the reported issue. I request you to please provide more details for the same. It would be helpful if you could share some screenshot or video. It will help us in understanding the issue more better.

**Comment by mayur-bhandari** [comment]
Closed due to inactivity.
