### ISSUE TITLE
cannot send voice message

### ISSUE THREAD

**Issue by davidweica** [cometchat-pro-samples/react-native-chat-app#6]

**Comment by mayur-bhandari** [comment]
What error are you getting. I tried sending a voice message and was successful in doing so. Kindly paste the error you get so that i can help you with it.

**Comment by davidweica** [comment]
I couldn’t find the option in action menu to leave and send voice message. Only image and documents

**Comment by mayur-bhandari** [comment]
The sample is just for demonstration of what functionality is available and how to use it. Just like image and file sending option you can create an option to send voice messages.
