### ISSUE TITLE
Messages appear in wrong place

### ISSUE THREAD

**Issue by ianidi** [cometchat-pro-samples/react-native-chat-app#7]
Hi!

When I message in group chat, messages appear on the right place and I can see the delivery indicator. However when I message to users, messages appear on the left side, like if it was not my own messages.

Personal chat:
<img width="366" alt="Снимок экрана 2020-01-13 в 10 20 08" src="https://user-images.githubusercontent.com/51965970/72238364-8d758800-35ee-11ea-8d1c-492497f5bb3b.png">

Group chat:
<img width="375" alt="Снимок экрана 2020-01-13 в 10 22 27" src="https://user-images.githubusercontent.com/51965970/72238386-a1b98500-35ee-11ea-88c2-231104918814.png">

**Comment by mayur-bhandari** [comment]
Hello @ianidi, we are sorry for the late response. We have updated our code and now the messages would be aligned properly in both one-on-one and group conversation. Can you please pull the latest code and let us know if the messages appear in the correct place?

**Comment by mayur-bhandari** [comment]
This issue has been fixed and the repository has been updated.
